/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => CanvasViewerPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var VIEW_TYPE_CANVAS_VIEWER = "canvas-viewer-view";
var DEFAULT_SETTINGS = {
  autoOpen: true,
  viewPosition: "right",
  enableEdit: true,
  defaultEditMode: "preview",
  saveFileLocation: "current",
  customSavePath: ""
};
var CanvasViewerPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.viewerLeaf = null;
    this.canvasMonitorInterval = null;
    this.lastSelectedNodeId = null;
    this.isViewerEnabled = false;
  }
  async onload() {
    await this.loadSettings();
    this.isViewerEnabled = this.settings.autoOpen;
    this.registerView(
      VIEW_TYPE_CANVAS_VIEWER,
      (leaf) => new CanvasViewerView(leaf, this)
    );
    this.addCommand({
      id: "open-canvas-viewer",
      name: "\u6253\u5F00 Canvas \u5185\u5BB9\u67E5\u770B\u5668",
      callback: () => {
        this.setViewerEnabled(true);
      }
    });
    this.addCommand({
      id: "close-canvas-viewer",
      name: "\u5173\u95ED Canvas \u5185\u5BB9\u67E5\u770B\u5668",
      callback: () => {
        this.setViewerEnabled(false);
      }
    });
    this.registerEvent(
      this.app.workspace.on("active-leaf-change", (leaf) => {
        var _a;
        if (((_a = leaf == null ? void 0 : leaf.view) == null ? void 0 : _a.getViewType()) === "canvas") {
          this.injectCanvasControl(leaf.view);
          if (this.isViewerEnabled) {
            this.activateView();
            this.startMonitoringCanvas();
          }
        } else {
          this.stopMonitoringCanvas();
        }
      })
    );
    this.app.workspace.onLayoutReady(() => {
      this.updateAllCanvasButtons();
    });
    this.addSettingTab(new CanvasViewerSettingTab(this.app, this));
    console.log("Canvas Viewer \u63D2\u4EF6\u5DF2\u52A0\u8F7D");
  }
  // 注入 Canvas 控制按钮
  injectCanvasControl(canvasView, retryCount = 0) {
    if (!canvasView || canvasView.getViewType() !== "canvas")
      return;
    const contentEl = canvasView.contentEl;
    if (contentEl.querySelector(".canvas-viewer-float-btn"))
      return;
    const btn = contentEl.createEl("div", {
      cls: "clickable-icon canvas-viewer-float-btn",
      attr: { "aria-label": "\u5F00\u542F/\u5173\u95ED Canvas \u67E5\u770B\u5668" }
    });
    btn.style.position = "absolute";
    btn.style.top = "304px";
    btn.style.right = "8px";
    btn.style.zIndex = "10";
    btn.style.backgroundColor = "var(--background-primary)";
    btn.style.boxShadow = "0 2px 8px rgba(0,0,0,0.2)";
    btn.style.borderRadius = "8px";
    btn.style.padding = "6px";
    btn.style.width = "34px";
    btn.style.height = "34px";
    btn.style.display = "flex";
    btn.style.alignItems = "center";
    btn.style.justifyContent = "center";
    btn.style.cursor = "pointer";
    btn.style.transition = "all 0.2s ease";
    btn.style.border = "1px solid var(--background-modifier-border)";
    btn.onmouseenter = () => {
      btn.style.transform = "scale(1.1)";
      btn.style.boxShadow = "0 4px 12px rgba(0,0,0,0.3)";
    };
    btn.onmouseleave = () => {
      btn.style.transform = "scale(1)";
      btn.style.boxShadow = "0 2px 8px rgba(0,0,0,0.2)";
    };
    this.updateControlBtnIcon(btn);
    btn.addEventListener("click", (e) => {
      e.stopPropagation();
      this.toggleViewerState(btn);
    });
  }
  updateControlBtnIcon(btn) {
    const iconName = this.isViewerEnabled ? "message-square-more" : "message-square-lock";
    btn.empty();
    (0, import_obsidian.setIcon)(btn, iconName);
    if (this.isViewerEnabled) {
      btn.addClass("is-active");
      btn.style.color = "var(--text-on-accent)";
      btn.style.backgroundColor = "var(--interactive-accent)";
      btn.style.borderColor = "var(--interactive-accent)";
      btn.setAttribute("aria-label", "\u5173\u95ED\u67E5\u770B\u5668");
    } else {
      btn.removeClass("is-active");
      btn.style.color = "var(--text-muted)";
      btn.style.backgroundColor = "var(--background-primary)";
      btn.style.borderColor = "var(--background-modifier-border)";
      btn.setAttribute("aria-label", "\u5F00\u542F\u67E5\u770B\u5668");
    }
  }
  async toggleViewerState(btn) {
    const newState = !this.isViewerEnabled;
    await this.setViewerEnabled(newState);
    this.updateControlBtnIcon(btn);
  }
  async setViewerEnabled(enabled) {
    this.isViewerEnabled = enabled;
    this.settings.autoOpen = enabled;
    await this.saveSettings();
    if (enabled) {
      await this.activateView();
      this.startMonitoringCanvas();
      new import_obsidian.Notice("Canvas \u67E5\u770B\u5668\u5DF2\u5F00\u542F");
    } else {
      this.stopMonitoringCanvas();
      this.deactivateView();
      new import_obsidian.Notice("Canvas \u67E5\u770B\u5668\u5DF2\u5173\u95ED");
    }
    this.updateAllCanvasButtons();
  }
  updateAllCanvasButtons() {
    const leaves = this.app.workspace.getLeavesOfType("canvas");
    leaves.forEach((leaf) => {
      const view = leaf.view;
      if (!view.contentEl.querySelector(".canvas-viewer-float-btn")) {
        this.injectCanvasControl(view);
      } else {
        const btn = view.contentEl.querySelector(".canvas-viewer-float-btn");
        if (btn) {
          this.updateControlBtnIcon(btn);
        }
      }
    });
  }
  onunload() {
    this.stopMonitoringCanvas();
    this.deactivateView();
    const buttons = document.querySelectorAll(".canvas-viewer-float-btn");
    buttons.forEach((btn) => btn.remove());
    console.log("Canvas Viewer \u63D2\u4EF6\u5DF2\u5378\u8F7D");
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async activateView() {
    const { workspace } = this.app;
    let leaf = workspace.getLeavesOfType(VIEW_TYPE_CANVAS_VIEWER)[0];
    if (!leaf) {
      const targetLeaf = this.settings.viewPosition === "right" ? workspace.getRightLeaf(false) : workspace.getLeftLeaf(false);
      if (targetLeaf) {
        await targetLeaf.setViewState({
          type: VIEW_TYPE_CANVAS_VIEWER,
          active: true
        });
        leaf = targetLeaf;
      }
    }
    if (leaf) {
      workspace.revealLeaf(leaf);
      this.viewerLeaf = leaf;
    }
  }
  deactivateView() {
    const leaves = this.app.workspace.getLeavesOfType(VIEW_TYPE_CANVAS_VIEWER);
    leaves.forEach((leaf) => leaf.detach());
    this.viewerLeaf = null;
  }
  startMonitoringCanvas() {
    this.stopMonitoringCanvas();
    this.canvasMonitorInterval = window.setInterval(() => {
      this.checkCanvasSelection();
    }, 500);
  }
  stopMonitoringCanvas() {
    if (this.canvasMonitorInterval !== null) {
      window.clearInterval(this.canvasMonitorInterval);
      this.canvasMonitorInterval = null;
    }
    this.lastSelectedNodeId = null;
  }
  async checkCanvasSelection() {
    const activeView = this.app.workspace.getActiveViewOfType(import_obsidian.ItemView);
    if (!activeView || activeView.getViewType() !== "canvas") {
      return;
    }
    try {
      const canvasView = activeView;
      const canvas = canvasView.canvas;
      if (!canvas || !canvas.selection) {
        return;
      }
      const selectedNodes = Array.from(canvas.selection);
      if (selectedNodes.length === 0) {
        return;
      }
      const selectedNode = selectedNodes[0];
      if (!selectedNode || !selectedNode.id) {
        return;
      }
      if (this.viewerLeaf && this.viewerLeaf.view instanceof CanvasViewerView) {
        if (this.viewerLeaf.view.isPinned) {
          return;
        }
      }
      if (selectedNode.id === this.lastSelectedNodeId) {
        return;
      }
      this.lastSelectedNodeId = selectedNode.id;
      await this.updateViewerContent(selectedNode, canvasView);
    } catch (error) {
      console.error("\u68C0\u67E5 Canvas \u9009\u4E2D\u72B6\u6001\u65F6\u51FA\u9519:", error);
    }
  }
  async updateViewerContent(node, canvasView) {
    const viewerLeaf = this.viewerLeaf;
    if (!viewerLeaf) {
      return;
    }
    const view = viewerLeaf.view;
    if (view instanceof CanvasViewerView) {
      await view.displayNodeContent(node, canvasView);
    }
  }
};
var CanvasViewerView = class extends import_obsidian.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.currentNode = null;
    this.currentCanvasView = null;
    this.editMode = "preview";
    this.currentFile = null;
    this.embeddedLeaf = null;
    this.temporaryFile = null;
    this.fileModifyCallback = null;
    this.isPinned = false;
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_CANVAS_VIEWER;
  }
  getDisplayText() {
    return "Canvas \u5185\u5BB9\u67E5\u770B\u5668";
  }
  getIcon() {
    return "file-text";
  }
  async onOpen() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("canvas-viewer-container");
    this.viewContentEl = container.createEl("div", { cls: "canvas-viewer-content" });
    this.showPlaceholder();
  }
  // 辅助方法：创建带有图钉的头部
  createHeaderWithPin(wrapper, typeText, extraText = "", openFile = null) {
    const header = wrapper.createEl("div", { cls: "node-header" });
    const leftContainer = header.createEl("div", { cls: "node-header-left" });
    const info = leftContainer.createEl("div", { cls: "node-info" });
    info.createEl("strong", { text: typeText });
    if (extraText) {
      const nameEl = leftContainer.createEl("div", { cls: "file-name" });
      nameEl.createEl("span", { text: extraText });
    }
    const pinBtn = leftContainer.createEl("div", {
      cls: "clickable-icon node-pin-btn",
      attr: { "aria-label": "\u56FA\u5B9A\u5F53\u524D\u89C6\u56FE" }
    });
    const updatePinState = () => {
      const iconName = this.isPinned ? "pin" : "pin-off";
      pinBtn.empty();
      (0, import_obsidian.setIcon)(pinBtn, iconName);
      if (this.isPinned) {
        pinBtn.addClass("is-active");
        pinBtn.setAttribute("aria-label", "\u53D6\u6D88\u56FA\u5B9A");
      } else {
        pinBtn.removeClass("is-active");
        pinBtn.setAttribute("aria-label", "\u56FA\u5B9A\u5F53\u524D\u89C6\u56FE");
      }
    };
    updatePinState();
    pinBtn.addEventListener("click", (e) => {
      e.stopPropagation();
      this.isPinned = !this.isPinned;
      updatePinState();
      if (this.isPinned) {
        new import_obsidian.Notice("Canvas \u67E5\u770B\u5668\u5DF2\u56FA\u5B9A");
      } else {
        new import_obsidian.Notice("Canvas \u67E5\u770B\u5668\u5DF2\u53D6\u6D88\u56FA\u5B9A");
      }
    });
    if (openFile) {
      const openBtn = leftContainer.createEl("div", {
        cls: "clickable-icon node-open-btn",
        attr: { "aria-label": "\u5728\u65B0\u6807\u7B7E\u9875\u4E2D\u6253\u5F00" }
      });
      (0, import_obsidian.setIcon)(openBtn, "folder-open-dot");
      openBtn.style.opacity = "0.6";
      openBtn.style.cursor = "pointer";
      openBtn.onmouseenter = () => openBtn.style.opacity = "1";
      openBtn.onmouseleave = () => openBtn.style.opacity = "0.6";
      openBtn.addEventListener("click", (e) => {
        e.stopPropagation();
        this.app.workspace.getLeaf("tab").openFile(openFile);
      });
    }
    return header;
  }
  async onClose() {
    if (this.embeddedLeaf) {
      this.embeddedLeaf.detach();
      this.embeddedLeaf = null;
    }
    if (this.fileModifyCallback) {
      this.app.vault.off("modify", this.fileModifyCallback);
      this.fileModifyCallback = null;
    }
    await this.cleanupTemporaryFile();
    this.viewContentEl.empty();
  }
  async cleanupTemporaryFile() {
    if (this.temporaryFile) {
      try {
        await this.app.vault.delete(this.temporaryFile);
      } catch (e) {
        console.debug("\u6E05\u7406\u4E34\u65F6\u6587\u4EF6\u5931\u8D25(\u53EF\u80FD\u5DF2\u5220\u9664):", e);
      }
      this.temporaryFile = null;
    }
  }
  showPlaceholder() {
    this.viewContentEl.empty();
    this.viewContentEl.createEl("div", {
      cls: "canvas-viewer-placeholder",
      text: "\u8BF7\u5728 Canvas \u4E2D\u9009\u62E9\u4E00\u4E2A\u6587\u672C\u6846\u6216\u6587\u4EF6\u8282\u70B9"
    });
  }
  async displayNodeContent(node, canvasView) {
    this.viewContentEl.empty();
    this.currentNode = node;
    this.currentCanvasView = canvasView;
    this.editMode = this.plugin.settings.defaultEditMode;
    try {
      if (node.text !== void 0) {
        await this.displayTextNode(node);
      } else if (node.file) {
        await this.displayFileNode(node, canvasView);
      } else if (node.url) {
        await this.displayLinkNode(node);
      } else if (node.type === "group") {
        await this.displayGroupNode(node);
      } else {
        this.viewContentEl.createEl("div", {
          cls: "canvas-viewer-info",
          text: `\u6682\u4E0D\u652F\u6301\u7684\u8282\u70B9\u7C7B\u578B: ${node.type || "unknown"}`
        });
      }
    } catch (error) {
      console.error("\u663E\u793A\u8282\u70B9\u5185\u5BB9\u65F6\u51FA\u9519:", error);
      this.viewContentEl.createEl("div", {
        cls: "canvas-viewer-error",
        text: "\u663E\u793A\u5185\u5BB9\u65F6\u51FA\u9519"
      });
    }
  }
  async displayTextNode(node) {
    const wrapper = this.viewContentEl.createEl("div", { cls: "canvas-viewer-text-node" });
    const header = this.createHeaderWithPin(wrapper, "\u6587\u672C\u8282\u70B9");
    const leftContainer = header.querySelector(".node-header-left");
    if (leftContainer) {
      const saveBtn = leftContainer.createEl("div", {
        cls: "clickable-icon node-save-btn",
        attr: { "aria-label": "\u63D0\u53D6\u4E3A Markdown \u6587\u4EF6" }
      });
      (0, import_obsidian.setIcon)(saveBtn, "file-plus");
      saveBtn.style.opacity = "0.6";
      saveBtn.style.marginLeft = "8px";
      saveBtn.addEventListener("click", async (e) => {
        e.stopPropagation();
        await this.saveTextNodeAsFile(node);
      });
      saveBtn.onmouseenter = () => saveBtn.style.opacity = "1";
      saveBtn.onmouseleave = () => saveBtn.style.opacity = "0.6";
      const saveAsBtn = leftContainer.createEl("div", {
        cls: "clickable-icon node-save-as-btn",
        attr: { "aria-label": "\u53E6\u5B58\u4E3A Markdown \u6587\u4EF6..." }
      });
      (0, import_obsidian.setIcon)(saveAsBtn, "save");
      saveAsBtn.style.opacity = "0.6";
      saveAsBtn.style.marginLeft = "8px";
      saveAsBtn.addEventListener("click", (e) => {
        e.stopPropagation();
        const defaultName = this.extractDefaultFileName(node.text || "");
        new FileNameModal(this.app, defaultName, async (result) => {
          if (result) {
            await this.saveTextNodeAsFile(node, result);
          }
        }).open();
      });
      saveAsBtn.onmouseenter = () => saveAsBtn.style.opacity = "1";
      saveAsBtn.onmouseleave = () => saveAsBtn.style.opacity = "0.6";
    }
    if (node.color) {
      const info = header.querySelector(".node-info");
      if (info) {
        info.createEl("span", {
          cls: "node-color-indicator",
          attr: { "data-color": node.color }
        });
      }
    }
    const content = wrapper.createEl("div", { cls: "node-content" });
    await this.cleanupTemporaryFile();
    const tempFileName = `Canvas Node ${node.id.substring(0, 6)}.md`;
    try {
      const existingFile = this.app.vault.getAbstractFileByPath(tempFileName);
      if (existingFile) {
        await this.app.vault.delete(existingFile);
      }
      this.temporaryFile = await this.app.vault.create(tempFileName, node.text || "");
      await this.renderFileContent(this.temporaryFile, content, true, node);
    } catch (error) {
      console.error("\u521B\u5EFA\u4E34\u65F6\u6587\u4EF6\u5931\u8D25:", error);
      content.createEl("div", {
        cls: "canvas-viewer-error",
        text: "\u65E0\u6CD5\u521B\u5EFA\u7F16\u8F91\u73AF\u5883: " + error.message
      });
    }
  }
  extractDefaultFileName(text) {
    let fileName = "\u672A\u547D\u540D\u7B14\u8BB0";
    const headerMatch = text.match(/^#+\s+(.*)$/m);
    if (headerMatch) {
      fileName = headerMatch[1].trim();
    } else {
      const firstLine = text.split("\n").find((line) => line.trim().length > 0);
      if (firstLine) {
        fileName = firstLine.trim();
      }
    }
    if (fileName.length > 50) {
      fileName = fileName.substring(0, 50) + "...";
    }
    fileName = fileName.replace(/[\\/:*?"<>|]/g, "");
    return fileName;
  }
  async saveTextNodeAsFile(node, customFileName = null) {
    var _a, _b;
    const text = node.text || "";
    if (!text.trim()) {
      new import_obsidian.Notice("\u8282\u70B9\u5185\u5BB9\u4E3A\u7A7A\uFF0C\u65E0\u6CD5\u4FDD\u5B58");
      return;
    }
    let fileName = customFileName;
    if (!fileName) {
      fileName = this.extractDefaultFileName(text);
    } else {
      fileName = fileName.replace(/[\\/:*?"<>|]/g, "");
    }
    const sourcePath = ((_b = (_a = this.currentCanvasView) == null ? void 0 : _a.file) == null ? void 0 : _b.path) || "";
    const folder = this.app.fileManager.getNewFileParent(sourcePath);
    let targetPath = (0, import_obsidian.normalizePath)(`${folder.path}/${fileName}.md`);
    let counter = 1;
    while (await this.app.vault.adapter.exists(targetPath)) {
      targetPath = (0, import_obsidian.normalizePath)(`${folder.path}/${fileName} (${counter}).md`);
      counter++;
    }
    try {
      const newFile = await this.app.vault.create(targetPath, text);
      new import_obsidian.Notice(`\u5DF2\u4FDD\u5B58\u4E3A: ${newFile.basename}`);
      if (this.currentCanvasView && this.currentCanvasView.canvas) {
        const canvas = this.currentCanvasView.canvas;
        const { x, y, width, height, color } = node;
        canvas.removeNode(node);
        const newNode = canvas.createFileNode({
          file: newFile,
          pos: { x, y },
          size: { width, height },
          save: true
        });
        if (color) {
          newNode.setColor(color);
          canvas.requestSave();
        }
        canvas.deselectAll();
        if (typeof canvas.select === "function") {
          canvas.select(newNode);
        } else if (canvas.selection && typeof canvas.selection.add === "function") {
          canvas.selection.add(newNode);
        }
        canvas.requestSave();
      }
    } catch (error) {
      console.error("\u4FDD\u5B58\u6587\u4EF6\u5931\u8D25:", error);
      new import_obsidian.Notice("\u4FDD\u5B58\u6587\u4EF6\u5931\u8D25: " + error.message);
    }
  }
  async displayFileNode(node, canvasView) {
    var _a;
    const wrapper = this.viewContentEl.createEl("div", { cls: "canvas-viewer-file-node" });
    let file = null;
    let filePath = "";
    if (node.file instanceof import_obsidian.TFile) {
      file = node.file;
      filePath = (file == null ? void 0 : file.path) || "";
    } else if (typeof node.file === "string") {
      filePath = node.file;
      if (filePath && !filePath.startsWith("/")) {
        const canvasFile = canvasView.file;
        if (canvasFile) {
          const canvasDir = ((_a = canvasFile.parent) == null ? void 0 : _a.path) || "";
          if (canvasDir) {
            filePath = `${canvasDir}/${filePath}`;
          }
        }
      }
      const abstractFile = this.app.vault.getAbstractFileByPath(filePath);
      if (abstractFile instanceof import_obsidian.TFile) {
        file = abstractFile;
      }
    }
    const imageExtensions = ["png", "jpg", "jpeg", "gif", "bmp", "svg", "webp"];
    const isImage = file && imageExtensions.includes(file.extension.toLowerCase());
    if (isImage) {
      wrapper.addClass("has-image");
    }
    let nodeTypeName = "\u6587\u4EF6\u8282\u70B9";
    if (file) {
      const ext = file.extension.toLowerCase();
      if (ext === "md") {
        nodeTypeName = "\u6587\u6863\u8282\u70B9";
      } else if (ext === "canvas") {
        nodeTypeName = "\u767D\u677F\u8282\u70B9";
      } else if (ext === "pdf") {
        nodeTypeName = "PDF \u8282\u70B9";
      } else if (imageExtensions.includes(ext)) {
        nodeTypeName = "\u56FE\u7247\u8282\u70B9";
      }
    }
    const displayName = file ? file.basename : typeof node.file === "string" ? node.file : "\u672A\u77E5\u6587\u4EF6";
    this.createHeaderWithPin(wrapper, nodeTypeName, displayName, file);
    const content = wrapper.createEl("div", { cls: "node-content" });
    if (file) {
      await this.renderFileContent(file, content);
    } else {
      content.createEl("div", {
        cls: "canvas-viewer-error",
        text: `\u6587\u4EF6\u4E0D\u5B58\u5728: ${filePath || "\u672A\u77E5\u8DEF\u5F84"}`
      });
    }
  }
  async displayLinkNode(node) {
    const wrapper = this.viewContentEl.createEl("div", { cls: "canvas-viewer-link-node" });
    const header = wrapper.createEl("div", { cls: "node-header" });
    const info = header.createEl("div", { cls: "node-info" });
    info.createEl("strong", { text: "\u7F51\u9875/\u94FE\u63A5\u8282\u70B9" });
    const content = wrapper.createEl("div", { cls: "node-content" });
    const linkContainer = content.createEl("div", { cls: "link-container" });
    linkContainer.createEl("div", { text: "URL: ", cls: "label" });
    linkContainer.createEl("a", {
      text: node.url,
      href: node.url,
      cls: "external-link"
    });
    const iframeContainer = content.createEl("div", { cls: "iframe-container" });
    iframeContainer.createEl("iframe", {
      attr: {
        src: node.url,
        sandbox: "allow-forms allow-presentation allow-same-origin allow-scripts allow-modals"
      }
    });
  }
  async displayGroupNode(node) {
    var _a;
    const wrapper = this.viewContentEl.createEl("div", { cls: "canvas-viewer-group-node" });
    const header = wrapper.createEl("div", { cls: "node-header" });
    const info = header.createEl("div", { cls: "node-info" });
    info.createEl("strong", { text: "\u5206\u7EC4 (Group)" });
    if (node.label) {
      info.createEl("span", { text: ` - ${node.label}` });
    }
    const content = wrapper.createEl("div", { cls: "node-content" });
    content.createEl("div", {
      text: `\u5206\u7EC4\u5305\u542B ${((_a = node.children) == null ? void 0 : _a.length) || 0} \u4E2A\u5B50\u8282\u70B9`,
      cls: "group-info"
    });
  }
  async renderFileContent(file, content, isTemporary = false, textNode = null) {
    content.empty();
    this.currentFile = file;
    const isMd = file.extension === "md";
    const isCanvas = file.extension === "canvas";
    const isPdf = file.extension.toLowerCase() === "pdf";
    const shouldEmbed = isMd || isPdf;
    if (!shouldEmbed && this.embeddedLeaf) {
      this.embeddedLeaf.detach();
      this.embeddedLeaf = null;
    }
    try {
      if (shouldEmbed) {
        content.addClass("native-embed-container");
        content.style.height = "100%";
        if (!this.embeddedLeaf) {
          this.embeddedLeaf = new import_obsidian.WorkspaceLeaf(this.app);
        }
        if (this.embeddedLeaf) {
          const openState = { active: false };
          if (isMd) {
            openState.state = { mode: "source" };
          }
          await this.embeddedLeaf.openFile(file, openState);
          const view = this.embeddedLeaf.view;
          if (view) {
            content.appendChild(view.containerEl);
            view.containerEl.style.height = "100%";
            view.containerEl.style.width = "100%";
            if (isMd && view instanceof import_obsidian.MarkdownView) {
              view.editor.refresh();
            }
            view.onResize();
          }
        }
        if (isTemporary && textNode) {
          if (this.fileModifyCallback) {
            this.app.vault.off("modify", this.fileModifyCallback);
            this.fileModifyCallback = null;
          }
          this.fileModifyCallback = async (modifiedFile) => {
            var _a, _b, _c;
            if (modifiedFile === file) {
              const newContent = await this.app.vault.read(file);
              if (typeof textNode.setText === "function") {
                textNode.setText(newContent);
              } else {
                textNode.text = newContent;
                if (typeof textNode.render === "function") {
                  textNode.render();
                } else if ((_b = (_a = this.currentCanvasView) == null ? void 0 : _a.canvas) == null ? void 0 : _b.requestFrame) {
                  this.currentCanvasView.canvas.requestFrame();
                }
              }
              this.currentNode.text = newContent;
              if ((_c = this.currentCanvasView) == null ? void 0 : _c.canvas) {
                this.currentCanvasView.canvas.requestSave();
              }
            }
          };
          this.app.vault.on("modify", this.fileModifyCallback);
        }
      } else if (isCanvas) {
        await this.renderCanvasThumbnail(file, content);
      } else {
        const imageExtensions = ["png", "jpg", "jpeg", "gif", "bmp", "svg", "webp"];
        if (imageExtensions.includes(file.extension.toLowerCase())) {
          const imgContainer = content.createEl("div", { cls: "canvas-viewer-image-container" });
          const img = imgContainer.createEl("img");
          img.src = this.app.vault.getResourcePath(file);
          img.alt = file.basename;
          this.enableImageZoomAndPan(imgContainer, img);
        } else {
          try {
            const fileContent = await this.app.vault.read(file);
            content.createEl("pre", { text: fileContent });
          } catch (e) {
            content.createEl("div", {
              cls: "canvas-viewer-info",
              text: `\u65E0\u6CD5\u9884\u89C8\u4E8C\u8FDB\u5236\u6587\u4EF6: ${file.extension}`
            });
          }
        }
      }
    } catch (error) {
      console.error("Render error:", error);
      content.createEl("div", {
        cls: "canvas-viewer-error",
        text: "\u65E0\u6CD5\u8BFB\u53D6\u6216\u6E32\u67D3\u6587\u4EF6\u5185\u5BB9: " + error.message
      });
    }
  }
  async renderCanvasThumbnail(file, container) {
    try {
      const content = await this.app.vault.read(file);
      const data = JSON.parse(content);
      if (!data.nodes || data.nodes.length === 0) {
        container.createEl("div", { text: "\u7A7A\u767D\u767D\u677F", cls: "canvas-viewer-info" });
        return;
      }
      const nodes = data.nodes;
      const edges = data.edges || [];
      let minX = Infinity, minY = Infinity, maxX = -Infinity, maxY = -Infinity;
      nodes.forEach((node) => {
        minX = Math.min(minX, node.x);
        minY = Math.min(minY, node.y);
        maxX = Math.max(maxX, node.x + node.width);
        maxY = Math.max(maxY, node.y + node.height);
      });
      const padding = 100;
      minX -= padding;
      minY -= padding;
      maxX += padding;
      maxY += padding;
      const width = maxX - minX;
      const height = maxY - minY;
      const svg = document.createElementNS("http://www.w3.org/2000/svg", "svg");
      svg.setAttribute("viewBox", `${minX} ${minY} ${width} ${height}`);
      svg.setAttribute("width", "100%");
      svg.setAttribute("height", "100%");
      svg.setAttribute("preserveAspectRatio", "xMidYMid meet");
      edges.forEach((edge) => {
        const fromNode = nodes.find((n) => n.id === edge.fromNode);
        const toNode = nodes.find((n) => n.id === edge.toNode);
        if (fromNode && toNode) {
          const x1 = fromNode.x + fromNode.width / 2;
          const y1 = fromNode.y + fromNode.height / 2;
          const x2 = toNode.x + toNode.width / 2;
          const y2 = toNode.y + toNode.height / 2;
          const line = document.createElementNS("http://www.w3.org/2000/svg", "line");
          line.setAttribute("x1", String(x1));
          line.setAttribute("y1", String(y1));
          line.setAttribute("x2", String(x2));
          line.setAttribute("y2", String(y2));
          line.setAttribute("stroke", "#555");
          line.setAttribute("stroke-width", "4");
          line.setAttribute("opacity", "0.5");
          svg.appendChild(line);
        }
      });
      nodes.forEach((node) => {
        const rect = document.createElementNS("http://www.w3.org/2000/svg", "rect");
        rect.setAttribute("x", String(node.x));
        rect.setAttribute("y", String(node.y));
        rect.setAttribute("width", String(node.width));
        rect.setAttribute("height", String(node.height));
        rect.setAttribute("rx", "16");
        let fill = "#333";
        const colorMap = {
          "1": "#e74c3c",
          // Red
          "2": "#e67e22",
          // Orange
          "3": "#f39c12",
          // Yellow
          "4": "#27ae60",
          // Green
          "5": "#3498db",
          // Cyan/Blue
          "6": "#9b59b6"
          // Purple
        };
        if (node.color) {
          if (node.color.startsWith("#")) {
            fill = node.color;
          } else if (colorMap[node.color]) {
            fill = colorMap[node.color];
          }
        } else {
          if (node.type === "text")
            fill = "#2c3e50";
          else if (node.type === "file")
            fill = "#34495e";
          else if (node.type === "group")
            fill = "transparent";
        }
        rect.setAttribute("fill", fill);
        if (node.type === "group") {
          rect.setAttribute("stroke", "#666");
          rect.setAttribute("stroke-width", "4");
          rect.setAttribute("stroke-dasharray", "10,10");
        } else {
          rect.setAttribute("opacity", "0.8");
        }
        svg.appendChild(rect);
      });
      const wrapper = container.createEl("div", { cls: "canvas-thumbnail-wrapper" });
      wrapper.appendChild(svg);
    } catch (e) {
      console.error("\u89E3\u6790 Canvas \u7F29\u7565\u56FE\u5931\u8D25", e);
      container.createEl("div", { text: "\u9884\u89C8\u751F\u6210\u5931\u8D25", cls: "canvas-viewer-error" });
    }
  }
  // 移除 updateFilePreview，不再需要
  async updateFilePreview_removed(text, previewPane, file) {
  }
  // 图片缩放和平移功能
  enableImageZoomAndPan(container, img) {
    let scale = 1;
    let panning = false;
    let pointX = 0;
    let pointY = 0;
    let startX = 0;
    let startY = 0;
    container.style.overflow = "hidden";
    container.style.position = "relative";
    container.style.height = "100%";
    container.style.width = "100%";
    container.style.display = "flex";
    container.style.alignItems = "center";
    container.style.justifyContent = "center";
    img.style.transformOrigin = "center center";
    img.style.transition = "transform 0.1s ease-out";
    img.style.maxWidth = "100%";
    img.style.maxHeight = "100%";
    img.style.cursor = "grab";
    const updateTransform = () => {
      img.style.transform = `translate(${pointX}px, ${pointY}px) scale(${scale})`;
    };
    container.onwheel = (e) => {
      e.preventDefault();
      const xs = (e.clientX - container.getBoundingClientRect().left - container.offsetWidth / 2) / scale;
      const ys = (e.clientY - container.getBoundingClientRect().top - container.offsetHeight / 2) / scale;
      const delta = e.deltaY > 0 ? 0.9 : 1.1;
      const newScale = scale * delta;
      if (newScale < 0.5 || newScale > 10)
        return;
      scale = newScale;
      updateTransform();
    };
    container.onmousedown = (e) => {
      e.preventDefault();
      startPanning(e.clientX, e.clientY);
    };
    const startPanning = (clientX, clientY) => {
      panning = true;
      startX = clientX - pointX;
      startY = clientY - pointY;
      img.style.cursor = "grabbing";
      img.style.transition = "none";
    };
    window.onmousemove = (e) => {
      if (!panning)
        return;
      e.preventDefault();
      pointX = e.clientX - startX;
      pointY = e.clientY - startY;
      updateTransform();
    };
    window.onmouseup = () => {
      if (panning) {
        panning = false;
        img.style.cursor = "grab";
        img.style.transition = "transform 0.1s ease-out";
      }
    };
    container.ondblclick = () => {
      scale = 1;
      pointX = 0;
      pointY = 0;
      updateTransform();
    };
  }
};
var CanvasViewerSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Canvas Viewer \u8BBE\u7F6E" });
    new import_obsidian.Setting(containerEl).setName("\u81EA\u52A8\u6253\u5F00\u67E5\u770B\u5668").setDesc("\u5F53\u6253\u5F00 Canvas \u6587\u4EF6\u65F6\u81EA\u52A8\u6253\u5F00\u5185\u5BB9\u67E5\u770B\u5668").addToggle((toggle) => toggle.setValue(this.plugin.settings.autoOpen).onChange(async (value) => {
      this.plugin.settings.autoOpen = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("\u67E5\u770B\u5668\u4F4D\u7F6E").setDesc("\u8BBE\u7F6E\u5185\u5BB9\u67E5\u770B\u5668\u663E\u793A\u5728\u5DE6\u4FA7\u8FD8\u662F\u53F3\u4FA7").addDropdown((dropdown) => dropdown.addOption("right", "\u53F3\u4FA7").addOption("left", "\u5DE6\u4FA7").setValue(this.plugin.settings.viewPosition).onChange(async (value) => {
      this.plugin.settings.viewPosition = value;
      await this.plugin.saveSettings();
      if (this.plugin["viewerLeaf"]) {
        this.plugin.deactivateView();
        await this.plugin.activateView();
      }
    }));
    new import_obsidian.Setting(containerEl).setName("\u542F\u7528\u7F16\u8F91\u529F\u80FD").setDesc("\u5141\u8BB8\u5728\u67E5\u770B\u5668\u4E2D\u76F4\u63A5\u7F16\u8F91\u6587\u672C\u8282\u70B9\u548C MD \u6587\u4EF6").addToggle((toggle) => toggle.setValue(this.plugin.settings.enableEdit).onChange(async (value) => {
      this.plugin.settings.enableEdit = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("\u9ED8\u8BA4\u7F16\u8F91\u6A21\u5F0F").setDesc("\u70B9\u51FB\u7F16\u8F91\u6309\u94AE\u540E\u9ED8\u8BA4\u8FDB\u5165\u7684\u6A21\u5F0F\uFF08\u5B9E\u65F6\u9884\u89C8\uFF09").addDropdown((dropdown) => dropdown.addOption("preview", "\u5B9E\u65F6\u9884\u89C8\uFF08\u63A8\u8350\uFF09").addOption("source", "\u6E90\u7801\u6A21\u5F0F").setValue(this.plugin.settings.defaultEditMode).onChange(async (value) => {
      this.plugin.settings.defaultEditMode = value;
      await this.plugin.saveSettings();
    }));
  }
};
var FileNameModal = class extends import_obsidian.Modal {
  constructor(app, defaultName, onSubmit) {
    super(app);
    this.result = defaultName;
    this.onSubmit = onSubmit;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h1", { text: "\u8F93\u5165\u6587\u4EF6\u540D" });
    new import_obsidian.Setting(contentEl).setName("\u6587\u4EF6\u540D").addText(
      (text) => text.setValue(this.result).onChange((value) => {
        this.result = value;
      })
    );
    new import_obsidian.Setting(contentEl).addButton(
      (btn) => btn.setButtonText("\u4FDD\u5B58").setCta().onClick(() => {
        this.close();
        this.onSubmit(this.result);
      })
    );
    setTimeout(() => {
      const input = contentEl.querySelector("input");
      if (input)
        input.focus();
    }, 0);
    contentEl.addEventListener("keydown", (e) => {
      if (e.key === "Enter") {
        this.close();
        this.onSubmit(this.result);
      }
    });
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
